//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string BookingDesc { get; set; }
        public int BookingPrice { get; set; }
        public int PackageId { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
