//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public int UniqueId { get; set; }
        public int PackageId { get; set; }
        public int Transportation_id { get; set; }
        public int Guide_id { get; set; }
        public int Hotel_id { get; set; }
        public int City_id { get; set; }
        public int Package_price { get; set; }
        public int User_id { get; set; }
        public Nullable<int> No_of_days { get; set; }
        public System.DateTime Tour_Start_Date { get; set; }
    
        public virtual City City { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Transportation Transportation { get; set; }
        public virtual User User { get; set; }
        public virtual TourGuide TourGuide { get; set; }
    }
}
