//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class Payment
    {
        public int Id { get; set; }
        [Required]
        public string Name_on_card { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "{0} should be 16 digits long",MinimumLength =16)]
        public string Debit_card_Number { get; set; }
        [Required]
        public string Exp_Month { get; set; }
        [Required]
        public string Exp_Year { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public int Cvv { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
