//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class places_in_city
    {
        public int place_id { get; set; }
        public int CityId { get; set; }
        public string Activity { get; set; }
        public string Fav_place { get; set; }
        public byte[] image_path { get; set; }
    
        public virtual City City { get; set; }
    }
}
